<?php

/**
 * hook_menu
 */
function ms_crm_menu() {
    $items = array();

    $items['admin/config/system/crm-settings'] = array(
        'title' => 'Marketspace CRM settings Constant Contact',
        'description' => 'Setup Marketspace CRM Configuration',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('ms_crm_admin_settings'),
        'access arguments' => array('administer site configuration'),
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}

/**
 * admin settings form for constant contact
 */
function ms_crm_admin_settings() {
    $form = array();
    $form['ms_crm_constant_contact_key'] = array(
        '#type' => 'password',
        '#title' => t('Constant Contact Api Key'),
        '#default_value' => variable_get('ms_crm_constant_contact_key', ''),
        '#size' => 80,
        '#maxlength' => 400,
        '#description' => t("The key - sign in here <a href='%url'>mashery</a> to get it", array('%url' => 'https://constantcontact.mashery.com/io-docs')),
        '#required' => TRUE,
    );
    $form['ms_crm_constant_contact_token'] = array(
        '#type' => 'password',
        '#title' => t('Constant Contact Api Token'),
        '#default_value' => variable_get('ms_crm_constant_contact_token', ''),
        '#size' => 80,
        '#maxlength' => 400,
        '#description' => t("I guess/hope this is static. Could not find and endpoint to grab one..Weak api???
            The token - sign in here <a href='%url'>mashery</a> to get it", array('%url' => 'https://constantcontact.mashery.com/io-docs')),
        '#required' => TRUE,
    );
    $form['ms_crm_constant_contact_secret'] = array(
        '#type' => 'password',
        '#title' => t('Constant Contact Api Secret'),
        '#default_value' => variable_get('ms_crm_constant_contact_secret', ''),
        '#size' => 80,
        '#maxlength' => 400,
        '#description' => t("I guess this is static.
            The token - sign in here <a href='%url'>mashery</a> to get it", array('%url' => 'https://constantcontact.mashery.com/io-docs')),
        '#required' => TRUE,
    );
    $form['ms_crm_constant_contact_endpoint'] = array(
        '#type' => 'textfield',
        '#title' => t('Api Endpoint'),
        '#default_value' => variable_get('ms_crm_constant_contact_endpoint', ''),
        '#size' => 80,
        '#maxlength' => 400,
        '#description' => t("The enpdoint should be full url with version - sign in here <a href='%url'>mashery</a> to get it", array('%url' => 'https://constantcontact.mashery.com/io-docs')),
        '#required' => TRUE,
    );
    $form['ms_crm_constant_contact_appname'] = array(
        '#type' => 'textfield',
        '#title' => t('Name of App - may not be important'),
        '#default_value' => variable_get('ms_crm_constant_contact_appname', ''),
        '#size' => 80,
        '#maxlength' => 400,
        '#description' => t("The app name - sign in here <a href='%url'>mashery</a> to get it", array('%url' => 'https://constantcontact.mashery.com/io-docs')),
        '#required' => TRUE,
    );
    return system_settings_form($form);
}

/**
 * Implements hook_webform_component_info().
 */
function ms_crm_webform_component_info() {
    $components['ms_crm_cc'] = array(
        'label' => t('Constant Contact Element'),
        'description' => t('constant contact contact creation elements'),
        'features' => array(
            'group' => FALSE,
        ),
        'file' => 'components/ms_constant_contact.webform.inc',
    );
    return $components;
}
/**
 * hard code this form for now
 * @todo dynamically create using webform as the setup
 */
function ms_crm_seller_signup() {

}

function ms_crm_webform_component_presave(&$component)
{
    /*dpm($component);
    echo "<pre>post" . print_r($component,true) . "</pre>";
    die;*/
}
function ms_crm_webform_submission_presave($node, &$submission) {
    if($email = MS_Constant_Contact_Contacts_Submission::SubmissionHasEmail($submission->data)) {
        $cc_submission = new MS_Constant_Contact_Contacts_Submission($submission, $node);
        watchdog('cc_submission', 'submission <pre>%cc_submission</pre>', array('%cc_submission' => print_r($cc_submission, true)), WATCHDOG_INFO);
        $constant_contact = new MS_Individuals_Contacts();
        $constant_contact->postBody = $cc_submission->GetSubmission();
        $result = $constant_contact->post();
        watchdog('cc_post', 'post result <pre>%ccresult</pre> and post body <pre>%post_body</pre>',
            array('%ccresult' => print_r($result, true), '%post_body' => print_r($constant_contact->postBody, true)), WATCHDOG_INFO);
        if($result['error']['code'] == 201) {
            $registration = new MS_User_Email($email);
            $registration->RegisterLocalSellerUser();
        }
    }
//    dpm($email);
//    dpm($submission);
//    dpm($result);
//    dpm($constant_contact->postBody);
    //var_export($submission);
//    echo "<pre>submission" . print_r($submission, true) . "</pre>";
//    echo "<pre>post" . print_r($_POST,true) . "</pre>";
//    die;
}