<?php

/*
 * hook_menu
 */
function ms_reports_menu() {
    $items = array();
    $items['products-reports'] = array(
        'page callback' => 'RenderReportsChartsDashboard',
        'type' => MENU_CALLBACK,
        'access arguments' => array('access content'),
    );
    $items['products-reports-grid'] = array(
        'page callback' => 'RenderReportsGridDashboard',
        'type' => MENU_CALLBACK,
        'access arguments' => array('access content'),
    );
    return $items;
}

/**
 * @return array
 */
function ms_reports_theme($existing, $type, $theme, $path) {
    $items = array();
    $items['product_reports_charts_block'] = array(
        'path' => drupal_get_path('theme', 'cm') . '/templates',
        'template' => 'products-reports-charts-block',
        'variables' => array(
            'junk' => 123,
        ),
    );
    $items['products_reports_grid_block'] = array(
        'path' => drupal_get_path('theme', 'cm') . '/templates',
        'template' => 'products-reports-grid-block',
    );
    return $items;
}

function RenderReportsChartsDashboard() {
    global $user;
    $dashboard = new MS_Render_Reports();
    $dashboard->Uid = $user->uid;
    $dashboard->Method = "ReportsGrid";
    $dashboard->ListType = "AllOrders";
    $dashboard->ListTypeParameters = "all";
    $products = $dashboard->render();
    $active_item = isset($_GET['id']) ? $_GET['id'] : '';
    $dashboard->Method = "ProductChart";
    $dashboard->Products = $active_item;
    $report = $dashboard->render();
    $report_json = json_encode($report);
    drupal_add_js("jQuery(function () { jQuery('#ms-sales-chart').highcharts($report_json);});",
        array('type' => 'inline', 'scope' => 'footer', 'weight' => 5)
    );
    return theme(
        'product_reports_charts_block',
        array(
            'ms_products_reports_list' => $products,
            'ms_active_product_id' => $active_item,
            'ms_product_report_json' => $report,
        )
    );
}

function RenderReportsGridDashboard() {
    global $user;
    $dashboard = new MS_Render_Reports();
    $dashboard->Uid = $user->uid;
    $dashboard->Method = "ReportsGrid";
    $dashboard->ListType = "AllOrdersDetails";
    $dashboard->ListTypeParameters = "all";
    $products = $dashboard->render();
    return theme(
        'products_reports_grid_block',
        array(
            'ms_products_reports_list' => $products,
        )
    );
}