<?php
/**
 * Implements hook_webform_select_options_info().
 */
function es_webform_webform_select_options_info() {
  $options['payment_method'] = array(
    'title' => t('Payment methods'),
    'options callback' => 'payment_method_options',
  );
  $options['payment_status'] = array(
    'title' => t('Payment statuses'),
    'options callback' => 'payment_status_options',
  );

  return $options;
}

/**
 * Implements hook_webform_component_info().
 */
function es_webform_webform_component_info() {
  $components['es_webform'] = array(
    'label' => t('Magento Attribute'),
    'description' => t('Lets users pay before being able to submit a webform.'),
    'features' => array(
      'default_value' => FALSE,
      'required' => TRUE,
    ),
    'file' => 'es_webform.webform.inc',
  );

  return $components;
}
/* add js and css 
 * see webform.module line 1857 webform_client_form
 * function for a good example
 * any webform will be webform_client_form_(nid)
 * so webform_client_form_2
 */
function es_webform_form_alter(&$form, $form_state, $form_id){
  if($form_id == "webform_client_form_2") {
    /*$form['#attached'] = array(
     'js' => array(drupal_get_path('module', 'es_category') . '/js/toggle_category.js'),
      'css' => array(drupal_get_path('module', 'es_category') . '/css/custom_components.css'),
    );*/
    echo "<pre>" . print_r($form_state['input'],true) . "</pre>";
    echo "<p>formstate values submitted array</p>";
    unset($form_state['values']['submitted'][21]['categories']);
      echo "<pre>" . print_r($form_state['values']['submitted'],true) . "</pre>";

   }
}