<?php
/* 
 * hook_menu
 */
   function es_webform_menu() {
   	
	$items = array();
    $items['get_attribute_info'] = array(
      'page callback' => 'get_attribute_info_2',
 
      'type' => MENU_CALLBACK,
      	  'access callback' => 'user_access',
	  'access arguments' => array('access content'),
    );
    return $items;
  }
   
   function get_attribute_info_2() {
  $magento = new magento();
  $attribute = $magento->get_attribute_information($magento->decryptText(variable_get('session_id')), 206);
  ($attribute->is_required == 1 ? $required = 'Yes' : $required = 'No');
  $content = '<p id="edit-extra-attribute-info"><span>Frontend Name: ' . $attribute->frontend_label[0]->label 
    . '</span><br /><span>Form Type: ' . $attribute->frontend_input . '</span><br /><span>Required: ' 
    . $required . '</p>'; //$attribute->frontend_label[0]->label
  //echo "<pre>" . print_r($attribute,true) . "</pre>";
  //die;
  return $content;
}
/**
 * Implements hook_webform_select_options_info().
 */
/*function es_webform_webform_select_options_info() {
  $options['payment_method'] = array(
    'title' => t('Payment methods'),
    'options callback' => 'payment_method_options',
  );
  $options['payment_status'] = array(
    'title' => t('Payment statuses'),
    'options callback' => 'payment_status_options',
  );

  return $options;
}*/

/**
 * Implements hook_webform_component_info().
 */
function es_webform_webform_component_info() {
  $components['es_webform'] = array(
    'label' => t('Magento Attribute'),
    'description' => t('Lets users pay before being able to submit a webform.'),
    'features' => array(
      'default_value' => FALSE,
      'required' => TRUE,
    ),
    'file' => 'es_webform.webform.inc',
  );

  return $components;
}
/* add js and css 
 * see webform.module line 1857 webform_client_form
 * function for a good example
 * any webform will be webform_client_form_(nid)
 * so webform_client_form_2
 */
function es_webform_form_alter(&$form, $form_state, $form_id){
  if($form_id == "webform_component_edit_form") {
    //$form['validation']['#disabled'] = TRUE;
    //$form['validation']['#collapsed'] = TRUE;
  }
  if($form_id == "webform_client_form_2") {
    $form['#attached'] = array(
     'js' => array(drupal_get_path('module', 'es_category') . '/js/toggle_category.js'),
     'css' => array(drupal_get_path('module', 'es_category') . '/css/custom_components.css'),
      
    );

    if(isset($form_state['values']['submitted'])) {

    }

   }
}