<?php
function es_magento_custom_options_webform_component_info() {
  $components['es_magento_custom_options'] = array(
    'label' => t('Magento Custom Options'),
    'description' => t('Lets users create custom options for their products.'),
    'features' => array(
      'default_value' => FALSE,
      'required' => TRUE,
    ),
    'file' => 'es_magento_custom_options.webform.inc',
  );

  return $components;
}

/* add js and css 
 * see webform.module line 1857 webform_client_form
 * function for a good example
 * any webform will be webform_client_form_(nid)
 * so webform_client_form_2
 */
function es_magento_custom_options_form_alter(&$form, $form_state, $form_id){
	watchdog('es_magento_custom_options', 'The form id %formid', array('%formid' => $form_id), WATCHDOG_NOTICE, $link = NULL);
  if($form_id == 'webform_component_edit_form') {
    $form['#attached'] = array(
      //'js' => array(drupal_get_path('module', 'es_magento_custom_options') . '/js/toggle_category.js'),
      'css' => array(drupal_get_path('module', 'es_magento_custom_options') . '/css/es-custom-option-forms.css'),
    );
   }
}